blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('football.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

football/urls.py
from django.urls import path
from . import views

app_name = 'football'
urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:slug>', views.category, name='category'),
    path('article/<slug:slug>', views.article, name='article'),
    path('add-article', views.add_article, name='add-article'),
    path('sign-up', views.sign_up, name='sign-up'),
    path('sign-in', views.sign_in, name='sign-in'),
    path('sign-out', views.sign_out, name='sign-out'),
    path('dashboard', views.dashboard, name='dashboard'),
    #path('edit-user/<slug:username>', views.edit_user, name='edit-user'),
    #path('user-info/<slug:username>', views.user_info, name='user-info'),
    #path('edit-article/<slug:slug>', views.edit_article, name='edit-article'),
]

football/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone
from extensions.utils import datetime_to_jalali_str

# my managers

class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='P')

# my models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    picture = models.ImageField(upload_to='profile_images', verbose_name='تصویر')
    birthday = models.DateField(verbose_name='تاریخ تولد')

    class Meta:
        verbose_name = 'نویسنده'
        verbose_name_plural = 'نویسندگان'

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')
    position = models.IntegerField(verbose_name='جایگاه')

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['position']

    def __str__(self):
        return self.name


class Article(models.Model):
    STATUS_CHOICES = (
        ('D', 'پیش نویس'),
        ('P', 'منتشر شده')
    )

    title = models.CharField(max_length=100, verbose_name='عنوان')
    author = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True,
        related_name='articles', verbose_name='نویسنده')
    content = models.TextField(verbose_name='محتوا')
    thumbnail = models.ImageField(upload_to='images', verbose_name='تصویر')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله')
    categories = models.ManyToManyField(Category, related_name='articles',
        verbose_name='دسته بندی ها')
    publish = models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name='وضعیت')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def jpublish(self):
        return datetime_to_jalali_str(self.publish)
    jpublish.short_description = 'زمان انتشار'

    def __str__(self):
        return self.title

    objects = ArticleManager()

football/forms.py
from django import forms
from .models import Category, Article, UserProfile
from django.contrib.auth.models import User
from django.utils import timezone

class DateInput(forms.DateInput): #This is a widget
    input_type = 'date'


class DateTimeInput(forms.DateTimeInput): #This is a widget
    input_type = 'datetime-local'


class ArticleForm(forms.ModelForm):
    publish = forms.DateTimeField(initial=timezone.now, label='زمان انتشار')

    class Meta:
        model = Article
        fields = ('title', 'content', 'thumbnail', 'slug',
            'categories', 'publish', 'status')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='رمز عبور')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    birthday = forms.DateField(widget=DateInput, label='تاریخ تولد')

    class Meta:
        model = UserProfile
        fields = ('picture', 'birthday')

football/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Category, Article, UserProfile
from django.core.paginator import Paginator
from .forms import ArticleForm, UserForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from datetime import datetime

# Create your helper functions here.

def visitor_cookie_handler(request, response):
    visits = int(request.COOKIES.get('visits', '1'))
    last_visit_cookie = request.COOKIES.get('last_visit' ,str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 0:
        visits += 1
        response.set_cookie('last_visit', str(datetime.now()))
    else:
        response.set_cookie('last_visit', last_visit_cookie)    
    response.set_cookie('visits', visits)


# Create your views here.

def home(request):
    article_list = Article.objects.published()
    paginator = Paginator(article_list, 3)
    page_number = request.GET.get('page', 1)
    articles = paginator.get_page(page_number)
    context = {
        'articles': articles,
        'active': 'home'
    }
    response = render(request, 'football/home.html', context)
    visitor_cookie_handler(request, response)
    return response


def article(request, slug):
    context = {
        'article': get_object_or_404(Article.objects.published(), slug=slug),
        'active': None
    }
    return render(request, 'football/article.html', context)


def category(request, slug):
    category_obj = get_object_or_404(Category, slug=slug)
    article_list = category_obj.articles.published()
    paginator = Paginator(article_list, 3)
    page_number = request.GET.get('page', 1)
    articles = paginator.get_page(page_number)
    context = {
        'articles': articles,
        'active': slug
    }
    return render(request, 'football/home.html', context)


@login_required
def add_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = request.user.profile
            form.save(commit=True)
            return HttpResponseRedirect('/football')
        else:
            pass
            #print(form.errors)
    else:
        form = ArticleForm()
    
    context = {'form': form}
    return render(request, 'football/add_article.html', context)


def sign_up(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user        
            profile.save()
            login(request, user)

        else:
            pass
            #print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'football/sign_up.html', context)


def sign_in(request):
    error_message = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/football/dashboard')
            else:
                error_message = 'حساب کاربری شما فعال نیست'
        else:
            error_message = 'نام کاربری یا رمز عبور صحیح نیست'
    
    context = {'error_message': error_message}
    return render(request, 'football/sign_in.html', context)


@login_required
def sign_out(request):
    logout(request)
    return HttpResponseRedirect('/football')


@login_required
def dashboard(request):
    profile = request.user.profile
    article_list = profile.articles.published()
    paginator = Paginator(article_list, 3)
    page_number = request.GET.get('page', 1)
    articles = paginator.get_page(page_number)
    context = {
        'profile': profile,
        'articles': articles,
    }
    return render(request, 'football/dashboard.html', context)

templates/football/add_article.html
{% extends 'football/base_forms.html' %}
{% load static %}

{% block head %}
    <title>Add New Article</title>
    <link rel='stylesheet' href='{% static "football/css/add_article.css" %}'>
{% endblock %}

{% block form_title %}افزودن مقاله جدید{% endblock %}

{% block form_body %}
    <form id="article_form" class='p-2 m-2' method="post" 
    action="{% url 'football:add-article' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            {% for error in field.errors %}
            <div class='text-right alert alert-danger alert-dismissible fade show'>
                {{error}}
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            </div>
            {% endfor %}
        <div class='row text-right p-2'>
            {{field.help_text}}
            <div class='col-sm-3'>{{field.label_tag}}</div>
            <div class='col-sm-9'>{{field}}</div>
        </div>
        {% endfor %}
        <div class='text-center'>
            <button type="submit" class='btn btn-success py-1'>ایجاد مقاله</button>
        </div>
    </form>
{% endblock %}

templates/football/article.html
{% extends 'football/base_articles.html' %}
{% load static %}
{% load base_filters %}

{% block head %}
    <title>Article</title>
	<link rel='stylesheet' href='{% static "football/css/article.css" %}'>
{% endblock %}

{% block content %}
	<article class='w-100 p-3'>
        <img src='{{article.thumbnail.url}}' class='d-block img-fluid img-thumbnail my-2 mx-auto article-img'>
        <div class='container card my-3 p-3 mx-auto shadow article'>
                 
            <p class='font-weight-bold text-right m-1 title'>{{article.title}}</p>
            <hr class='m-2'>
            <p class='text-justify m-1'>{{article.content|linebreaksbr}}</p>
            <hr class='m-2'>
            <p class='small text-right m-1'>نوشته شده توسط {{article.author}}</p>
            <p class='small text-right m-1'>تاریخ انتشار: {{article.jpublish}}</p>
            <p class='small text-right m-1'>
                {% for category in article.categories.all %}
                <span>#{{category.name|underscored}}</span>
                {% endfor %}
            </p>            
        </div>
	</article>	
{% endblock %}

templates/football/article_card.html
{% load base_filters %}
<article class='card m-2 shadow article'>
    <img src='{{article.thumbnail.url}}' class='img-thumbnail card-img-top article-img'>
    
    <div class='p-2'>
        <p class='font-weight-bold text-right m-1 title'>{{article.title}}</p>
        <hr class='m-2'>
        <p class='text-justify m-1'>{{article.content|truncatewords:40}}</p>
        <hr class='m-2'>
        <p class='small text-right m-1'>نوشته شده توسط {{article.author}}</p>
        <p class='small text-right m-1'>تاریخ انتشار: {{article.jpublish}}</p>
        <p class='small text-right m-1'>
            {% for category in article.categories.all %}
            <span>#{{category.name|underscored}}</span>
            {% endfor %}
        </p>
        <a href='{% url "football:article" article.slug %}' class="btn btn-primary continue" role="button">ادامه مطلب &larr;</a>
    </div>
</article>

templates/football/article_pagination.html
{% load base_filters %}
<div class='w-100 py-2 page-div m-0'>
    <ul class="pagination pagination-md justify-content-center p-0 flex-row-reverse flex-wrap">
        {% if articles.has_previous %}		
            <li class='page-item'><a class='page-link' href="?page={{articles.previous_page_number}}">قبلی &raquo;</a></li>
        {% else %}
            <li class='page-item disabled'><a class='page-link' href="#">قبلی &raquo;</a></li>
        {% endif %}
        
        {% for i in articles.paginator.page_range %}
            {% if i == articles.number %}
            <li class='page-item active'><a class='page-link' href="?page={{i}}">{{i|to_persian}}</a></li>
            {% else %}
            <li class='page-item'><a class='page-link' href="?page={{i}}">{{i|to_persian}}</a></li>
            {% endif %}
        {% endfor %}

        {% if articles.has_next %}
            <li class='page-item'><a class='page-link' href="?page={{articles.next_page_number}}">&laquo; بعدی</a></li>
        {% else %}
            <li class='page-item disabled'><a class='page-link' href="#">&laquo; بعدی</a></li>
        {% endif %}
    </ul>
</div>

templates/football/base_articles.html
<!DOCTYPE html>
{% load static %}
{% load base_tags %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel='stylesheet' href='{% static "football/css/base_articles.css" %}'>
	{% block head %}
    {% endblock %}

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	
</head>
<body>
	
	<header class="container-fluid m-0 p-0">
		{% top_navbar user %}
		<h1 class="text-white text-center px-2">{% title %}</h1>
		{% category_navbar active %}
	</header>
	<main class='m-0 content'>
        {% block content %}
        {% endblock %}
	</main>

</body>
</html>

templates/football/base_forms.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel='stylesheet' href='{% static "football/css/base_forms.css" %}'>
    {% block head %}
    {% endblock %}

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
	
	<main class='m-0 container-fluid p-2'>
        <div class='my-2 mx-auto text-center p-2 shadow text-white title'>
            {% block form_title %}
            {% endblock %}
        </div>
        <div class='mx-auto p-1 shadow text-white form-div'>
            {% block form_body %}
            {% endblock %}
        </div>
	</main>

</body>
</html>

templates/football/category_navbar.html
<nav class='navbar navbar-expand-lg navbar-dark categories p-0'>
    {% if active == "home" %}
    <a class="navbar-brand py-2 px-3 text-white m-0" style='background-color: #727272cb;' href='{% url "football:home" %}'> صفحه اصلی </a>
    {% else %}
    <a class="navbar-brand py-2 px-3 text-white m-0" href='{% url "football:home" %}'> صفحه اصلی </a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse m-0" id="collapsibleNavbar">
        <ul class='navbar-nav m-0'>
        {% for category in categories %}
            {% if active == category.slug %}
            <li class='nav-item py-1 px-2 text-center' style='background-color: #727272cb;'>
                <a class="nav-link text-white" href='{% url "football:category" category.slug %}'> {{category.name}} </a>
            </li>
            {% else %}
            <li class='nav-item py-1 px-2 text-center'>
                <a class="nav-link text-white" href='{% url "football:category" category.slug %}'> {{category.name}} </a>
            </li>
            {% endif %}
        {% endfor %}
        </ul>
    </div>
</nav>

templates/football/dashboard.html
<!DOCTYPE html>
{% load static %}
{% load base_filters %}
{% load base_tags %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel='stylesheet' href='{% static "football/css/dashboard.css" %}'>
    <link rel='stylesheet' href='{% static "football/css/article_card.css" %}'>
	<link rel='stylesheet' href='{% static "football/css/article_pagination.css" %}'>
    <title>Dashboard</title>

    <!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>
<body>
    <header class='row container-fluid p-0 m-0 text-white'>
        <div class='col-md-3 p-2'>
            <img src='{{profile.picture.url}}' class='d-block w-100 rounded-circle img-thumbnail profile-img'>
        </div>
        <div class='col-md-6 p-4'>
            <div class='container-fluid user-info'>
                <div class='row pu-2'>
                    <div class='col-sm-4 text-right p-2'>نام:</div>
                    <div class='col-sm-8 text-right p-2'>{{profile.user.first_name}}</div>
                </div>
                <div class='row'>
                    <div class='col-sm-4 text-right p-2'>نام خانوادگی:</div>
                    <div class='col-sm-8 text-right p-2'>{{profile.user.last_name}}</div>
                </div>
                <div class='row'>
                    <div class='col-sm-4 text-right p-2'>تعداد مقالات:</div>
                    <div class='col-sm-8 text-right p-2'>{{articles.paginator.count|to_persian}}</div>
                </div>
                <div class='row'>
                    <div class='col-sm-4 text-right p-2'>نام کاربری:</div>
                    <div class='col-sm-8 text-right p-2'>{{profile.user.username}}</div>
                </div>
                <div class='row'>
                    <div class='col-sm-4 text-right p-2'>ایمیل:</div>
                    <div class='col-sm-8 text-right p-2'>{{profile.user.email}}</div>
                </div>
                <div class='row'>
                    <div class='col-sm-4 text-right p-2'>تاریخ تولد:</div>
                    <div class='col-sm-8 text-right p-2'>{{profile.birthday|date_to_jalali}}</div>
                </div>
            </div>
        </div>
        <aside class='col-md-3 p-0 text-center d-flex flex-column justify-content-center'>
            <a type='button' class='d-block text-white m-1 p-2' href='{% url "football:home" %}'>
                بازگشت به صفحه اصلی
            </a>
            <a type='button' class='d-block text-white m-1 p-2' href='{% url "football:add-article" %}'>
                افزودن مقاله
            </a>
            <a type='button' class='d-block text-white m-1 p-2' href='#'>
                ویرایش اطلاعات
            </a>
            <a type='button' class='d-block text-white m-1 p-2' href='{% url "football:sign-out" %}'>
                خروج
            </a>
        </aside>
    </header>
    <main class='container-fluid p-0 m-0'>
        <div class='text-center p-2'>
            <span class='d-inline-block alert alert-info m-0'>مقالات نوشته شده</span>
        </div>
        <div class='w-100 d-flex flex-row-reverse flex-wrap justify-content-center align-items-start'>
        {% if articles %}
            {% for article in articles %}
                {% article_card article %}
            {% endfor %}
        {% else %}
        <div class='text-center p-2'>
            <span class='d-inline-block alert alert-warning m-0'>شما هنوز هیچ مقاله ای ننوشته اید</span>
        </div>
        {% endif %}
        </div>
        {% if articles.has_other_pages %}
            {% article_pagination articles %}
        {% endif %}
    </main>
</body>
</html>

templates/football/home.html
{% extends 'football/base_articles.html' %}
{% load static %}
{% load base_filters %}
{% load base_tags %}

{% block head %}
	<title>Home</title>
	<link rel='stylesheet' href='{% static "football/css/article_card.css" %}'>
	<link rel='stylesheet' href='{% static "football/css/article_pagination.css" %}'>
{% endblock %}

{% block content %}
	<div class='w-100 d-flex flex-row-reverse flex-wrap justify-content-center align-items-start'>
	{% for article in articles %}
		{% article_card article %}
	{% endfor %}
	</div>
	{% if articles.has_other_pages %}
		{% article_pagination articles %}
	{% endif %}
	<div class='alert alert-info text-right m-3'>
		<p>تعداد بازدید ها: {{request.COOKIES.visits}}</p>
		<p>آخرین بازدید: {{request.COOKIES.last_visit}}</p>
	</div>
{% endblock %}

templates/football/sign_in.html
{% extends 'football/base_forms.html' %}

{% block head %}
    <title>Sign in</title>
{% endblock %}

{% block form_title %}ورود{% endblock %}

{% block form_body %}
    {% if user.is_authenticated %}
        <div class='text-right alert alert-success m-3'>
            <p>شما با موفقیت وارد سایت شده اید</p>
            <a class='btn btn-link' href='{% url "football:home" %}'>بازگشت به صفحه اصلی</a>
            <a class='btn btn-link' href='{% url "football:add-article" %}'>افزودن مقاله جدید</a>
        </div>
    {% else %}
        <form id="article_form" class='p-2 m-2' method="post" 
        action='{% url "football:sign-in" %}' enctype="multipart/form-data">
            {% csrf_token %}

            {% if error_message %}
                <div class='text-right alert alert-danger alert-dismissible fade show'>
                    {{error_message}}
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                </div>
            {% endif %}
            <div class='row text-right p-2'>
                <div class='col-sm-4'>
                    <label for='username'>نام کاربری</label>
                </div>
                <div class='col-sm-8'>
                    <input type='text' id='username' name='username'>
                </div>
            </div>
            <div class='row text-right p-2'>
                <div class='col-sm-4'>
                    <label for='password'>رمز عبور</label>
                </div>
                <div class='col-sm-8'>
                    <input type='password' id='password' name='password'>
                </div>
            </div>
            <div class='text-center'>
                <button type="submit" class='btn btn-success py-1'>ورود</button>
            </div>
        </form>
    {% endif %}
{% endblock %}

templates/football/sign_up.html
{% extends 'football/base_forms.html' %}

{% block head %}
    <title>Sign up</title>
{% endblock %}

{% block form_title %}ثبت نام{% endblock %}

{% block form_body %}
    {% if user.is_authenticated %}
        <div class='text-right alert alert-success m-3'>
            <p>تبریک! شما با موفقیت در سایت ثبت نام کردید.</p>
            <a class='btn btn-link' href='{% url "football:home" %}'>بازگشت به صفحه اصلی</a>
            <a class='btn btn-link' href='{% url "football:add-article" %}'>افزودن مقاله جدید</a>
        </div>
    {% else %}
        <form id="article_form" class='p-2 m-2' method="post" 
        action='{% url "football:sign-up" %}' enctype="multipart/form-data">
            {% csrf_token %}
            <!-- User Form -->
            {% for field in user_form.visible_fields %}
                {% for error in field.errors %}
                    <div class='text-right alert alert-danger alert-dismissible fade show'>
                        {{error}}
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                    </div>
                {% endfor %}
                <div class='row p-2'>
                    <div class='col-sm-4 text-right'>{{field.label_tag}}</div>
                    <div class='col-sm-8 text-center'>{{field}}</div>
                </div>
            {% endfor %}

            <!-- Profile Form -->
            {% for field in profile_form.visible_fields %}
                {% for error in field.errors %}
                    <div class='text-right alert alert-danger alert-dismissible fade show'>
                        {{error}}
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                    </div>
                {% endfor %}
                <div class='row p-2'>
                    <div class='col-sm-4 text-right'>{{field.label_tag}}</div>
                    <div class='col-sm-8 text-center'>{{field}}</div>
                </div>
            {% endfor %}
            <div class='text-center'>
                <button type="submit" class='btn btn-success py-1'>ثبت نام</button>
            </div>
        </form>
    {% endif %}
{% endblock %}

templates/football/top_navbar.html
<nav class='navbar navbar-expand p-0 top-nav'>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class='navbar-nav m-0 p-0'>
        
        {% if user.is_authenticated %}
            <a class='navbar-brand m-0 p-2 px-3' href='{% url "football:dashboard" %}'>
                <img src='{{ user.profile.picture.url }}' alt='logo' width='32px'
                 height='32px' class='rounded-circle'>
            </a>
            <li class='nav-item py-1 px-2 text-center'>
                <a class="nav-link text-white" href='{% url "football:add-article" %}'>
                    <span>افزودن مقاله</span> <i class="fa">&#xf0fe;</i>
                </a>
            </li>

            <li class='nav-item py-1 px-2 text-center'>
                <a class="nav-link text-white" href='{% url "football:sign-out" %}'>
                    <span>خروج</span> <i class="fa">&#xf08b;</i>
                </a>
            </li>
        {% else %}
            <li class='nav-item py-1 px-2 text-center'>
                <a class="nav-link text-white" href='{% url "football:sign-up" %}'>
                    <span>ثبت نام</span> <i class="fa">&#xf234;</i>
                </a>
            </li>

            <li class='nav-item py-1 px-2 text-center'>
                <a class="nav-link text-white" href='{% url "football:sign-in" %}'>
                    <span>ورود</span> <i class="fa">&#xf090;</i>
                </a>
            </li>
        {% endif %}
        </ul>
    </div>
</nav>